"""add image_url column

Revision ID: 50d6265ce01a
Revises: 
Create Date: 2025-04-13 04:10:32.398777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '50d6265ce01a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tiktok_products', 'product_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tiktok_products', 'image_url',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.drop_column('tiktok_products', 'category')
    op.drop_column('tiktok_products', 'sold_1_month_ago')
    op.drop_column('tiktok_products', 'sold_today')
    op.drop_column('tiktok_products', 'list_velocity')
    op.drop_column('tiktok_products', 'product_description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tiktok_products', sa.Column('product_description', mysql.TEXT(), nullable=True))
    op.add_column('tiktok_products', sa.Column('list_velocity', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=True))
    op.add_column('tiktok_products', sa.Column('sold_today', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tiktok_products', sa.Column('sold_1_month_ago', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tiktok_products', sa.Column('category', mysql.VARCHAR(length=100), nullable=True))
    op.alter_column('tiktok_products', 'image_url',
               existing_type=sa.String(length=512),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('tiktok_products', 'product_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
